---

- hosts: all
  gather_facts: false
  vars:
    file_name: '/tmp/test'
  tasks:
    - file:
        path: '{{file_name}}'
        state: touch
    - name: install custom impi fact
      copy: src=/root/anaconda-ks.cfg dest=/root/anaconda-ks.cfg.2020
